enum MainMenuActions { 
  none,
  update,
  summarize,
  config,
  help
}

typedef FormSubmitCallback = void Function(dynamic data);

Map<String, String> vietnameseText = {
  'Vietnamese Wallet':'Sổ chi tiêu',
  'Create new transaction':'Thêm giao dịch mới',
  'Update wallet':'Cập nhật sổ',
  'Summarize':'Thống kê',
  'Summarize profit':'Thống kê thu nhập',
  'Filter':'Lọc',
  'Application Settings':'Thiết lập ứng dụng',
  'Support':'Hỗ trợ',
  'Contact: tranthehuythesecond@gmail.com':'Liên hệ: tranthehuythesecond@gmail.com',
  'Updated new config':'Đã cập nhật cài đặt mới',
  'Saved':'Đã thêm vào bộ nhớ',
  'Removed':'Đã xoá',
  'Remove all transaction':'Xoá hết các giao dịch',
  'Unit':'Đơn vị nhập',
  'Dong':'Đồng',
  'Thousand Dong':'Ngàn Đồng',
  'Language':'Ngôn ngữ',
  'Vietnamese':'Tiếng Việt',
  'English':'Tiếng Anh',
  'Save':'Lưu',
  'Cancel':'Huỷ',
  'Outcome: #1 Dong':'Chi phí: #1 đồng',
  'Income: #1 Dong':'Thu nhập: #1 đồng',
  'Sum: #1 Dong':'Tổng: #1 đồng',
  'Created at: #1':'Ngày tạo: #1',
  'Transaction type':'Loại giao dịch',
  'Outcome':'Chi tiêu',
  'Income':'Thu nhập',
  'Transaction name':'Tên giao dịch',
  'Amount':'Số tiền',
  'Created at #1':'Thời gian: #1',
  'New Transaction':'Giao dịch mới',
  'There is no transaction to show':'Danh sách rỗng',
  'This field is required': 'Vui lòng không để trống',
  'Filter Box': 'Bộ lọc',
  'Apply': 'Áp dụng',
};